// ts-rs writes one file per type; this re-exports them all from index.ts.
import { readdirSync, writeFileSync } from "node:fs";

const dir = new URL("../src/generated/", import.meta.url);
const types = readdirSync(dir).filter((f) => f.endsWith(".ts") && f !== "index.ts").sort();
const lines = types.map((f) => `export type * from "./${f}";`);
writeFileSync(new URL("index.ts", dir), `// Generated by scripts/write-index.mjs. Do not edit.\n${lines.join("\n")}\n`);
